[Interface]
PrivateKey = qCBVTzrK4uZSt/TJE2hiQozmLhi79Fxu0Ms34eQHfHc=
Address = 10.8.0.2/24
DNS = 8.8.8.8, 8.8.4.4

[Peer]
PublicKey = xTCiN8kF6ZP5MsLhD6afft83nikZwXWo/7nnoOO1vFg=
Endpoint = 112.161.54.7:51820
AllowedIPs = 223.130.195.0/24
PersistentKeepalive = 25
